# Deployment: gestiona el pod de PostgreSQL
# Si el pod se cae, Kubernetes lo reinicia automáticamente
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: default
spec:
  replicas: 1              # solo un pod (suficiente para desarrollo local)
  selector:
    matchLabels:
      app: postgres        # vincula este Deployment con sus pods por la etiqueta "app: postgres"
  template:
    metadata:
      labels:
        app: postgres      # etiqueta que se asigna al pod
    spec:
      containers:
        - name: postgres
          image: postgres:18        # imagen oficial de PostgreSQL 18
          ports:
            - containerPort: 5432  # puerto por defecto de PostgreSQL
          env:
            # Las credenciales se leen del Secret, no están en texto plano aquí
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # nombre del Secret que creamos en el paso 1
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/ # ruta donde PostgreSQL guarda los datos
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc  # el PVC que creamos en el paso 2