apiVersion: v1
kind: ConfigMap
metadata:
  name: pgwatch-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.database.user }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"