apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgwatch-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgwatch
  template:
    metadata:
      labels:
        app: pgwatch
    spec:
      initContainers:
        - name: migrations
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          command: ["alembic", "upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: pgwatch-config
                  key: DATABASE_URL
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: ENCRYPT_KEY
      containers:
        - name: pgwatch
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /health_check
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health_check
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: pgwatch-config
                  key: DATABASE_URL
            - name: ENCRYPT_KEY
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: ENCRYPT_KEY